### ISSUE TITLE
[SETTING] 기본 프로젝트 세팅

### ISSUE THREAD

**Issue by hwiwonK** [hwiwonK/MacC-Team-Maddori.Apple-Server#1]
## 💡 Issue

기본 서버 프로젝트 세팅 (express)

## 📝  Todo
- [x] node, express package.json에 추가
- [x] app.js 생성 후 서버 기본 코드 작성
- [x] .gitignore 파일 추가
- [x] nodemon 환경 설정 (수정할 때마다 자동으로 재 컴파일 되도록 함)
- [x] 폴더 구조 만들기
