### ISSUE TITLE
[FEAT] API 구현 - Setup 페이지(유저, 팀 등록, 합류, 나가기)

### ISSUE THREAD

**Issue by hwiwonK** [hwiwonK/MacC-Team-Maddori.Apple-Server#13]
## 💡 Issue

Setup 페이지에서 사용하는 API를 구현합니다.
빠른 개발을 위해 social login, jwt token은 사용하지 않고 username과 id 만을 이용해 로그인을 구현합니다.

## 📝  Todo
- [x] `POST /users/login` 유저 로그인 api 구현
- [x] `POST /users/join-team` 초대코드를 이용한 유저 팀 합류 api 구현
- [x] `POST /teams` 팀 등록 api 구현
- [x] `DELETE /users/team/{team_id}/leave` 유저 팀 나가기 api 구현
