### ISSUE TITLE
[FEAT] API 구현 - Home 페이지(팀 정보, 회고 정보 가져오기)

### ISSUE THREAD

**Issue by hwiwonK** [hwiwonK/MacC-Team-Maddori.Apple-Server#17]
## 💡 Issue

Home View에서 사용하는 api를 구현합니다.
- 팀 정보를 가져오는 api
   팀의 기본 정보(팀 이름, 팀 코드)와 유저가 해당 팀의 리더인지 여부
- 팀의 현재 회고 정보를 가져오는 api
   팀에서 진행 중인 현재 회고 정보 (id, 이름, 날짜, 상태, 키워드)

## 📝  Todo
- [x] 팀 정보를 가져오는 api `/teams/{team_id}`
- [x] 현재 회고 정보를 가져오는 api `/teams/{team_id}/reflections/current`
- [x] createTeam에서 current_reflection_id 추가하는 코드 구현
