### ISSUE TITLE
[CHORE] 코드 통일성 맞추기(response, 코드 스타일)

### ISSUE THREAD

**Issue by hwiwonK** [hwiwonK/MacC-Team-Maddori.Apple-Server#19]
## 💡 Issue

-  res.send를 res.json으로 변경하기
   res.send보다 res.json으로 응답을 보내는 것이 더 간결하고, 항상 response를 json으로 보내기에 변경한다.
- 함수 parameter를 (req,res,next)로 변경한다
   미들웨어를 사용할 경우 next가 parameter에 필요하다. 최종적으로는 미들웨어를 통해 리팩토링을 진행할 예정이기에 모든 함수에 next를 추가한다.
- 코드 스타일을 통일한다.
   https://platinum-theory-09d.notion.site/Javascript-Convention-bf7c99ff2f4b48fc8c1ea20e8e6d2667
- response의 형식을 아래와 같이 통일한다.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/67336936/200157568-ee8fd159-4835-4718-a557-e116e4982b10.png">

## 📝  Todo
- [x] res.json 으로 바꾸기
- [x] 함수(req,res,next)로 수정
- [x] response 형식 통일
- [x] 코드 스타일 통일
