### ISSUE TITLE
[TEST] 데이터베이스 테이블 구현 & 연결 테스트

### ISSUE THREAD

**Issue by hwiwonK** [hwiwonK/MacC-Team-Maddori.Apple-Server#3]
## 💡 Issue

sequelize로 테이블 생성 및 데이터 CRUD 테스트

## 📝  Todo
- [x] 테이블 생성 테스트
- [x] 테이블 정보 변경 테스트
- [x] 외래키, 기본키 설정 테스트
- [x] 더미데이터 활용 테스트 (seeder)
- [x] 레코드 삭제 시 cascade 설정 테스트
- [x] Create
- [x] Read
- [x] Update
- [x] Delete
- [x] 외래키 체크
