### ISSUE TITLE
[CHORE] response 형식 통일

### ISSUE THREAD

**Issue by hwiwonK** [hwiwonK/MacC-Team-Maddori.Apple-Server#62]
## 💡 Issue

response 형식 통일.
현재 depth가 필요하지 않은 곳에 depth가 들어가있고, user나 reflection 과 같은 공통된 response 내용의 형식이 다릅니다.
추후 백엔드 response 모델 객체 통일, 현재 클라이언트 response 모델 객체 통일을 위해 response 형식을 수정합니다.

## 📝  Todo
- [ ] depth 필요 없는 곳 depth 없애기
- [ ] user 정보 형식 통일
- [ ] reflection 정보 형식 통일

**Comment by hwiwonK** [comment]
코드 수정이 되면 클라쪽 수정이 필요하기 때문에, response format 수정은 잠시 중단합니다.

**Comment by unanchoi** [comment]
나중에 리팩토링 진행할 때 관련해서, response format을 정의하는 클래스를 정의하고 api에서 import 해서 사용하는 식으로 하면 좋을 것 같네요! ㅎ
