### ISSUE TITLE
[CHORE] 데이터베이스 수정

### ISSUE THREAD

**Issue by hwiwonK** [hwiwonK/MacC-Team-Maddori.Apple-Server#9]
## 💡 Issue

데이터 베이스 수정
- 클라이언트 뷰 이름과의 통일성을 위해 css 테이블 명을 feedback으로 변경합니다
- 유저가 탈퇴해도 피드백 내용이 남아있도록 결정했기 때문에 해당 테이블에서 cascade on delete 설정을 해제합니다

## 📝  Todo
- [x] css 테이블 -> feedback 테이블
- [x] feedback 테이블 cascade on delete 해제
- [x] 이모지 추가 가능하도록 data type utf8mb4로 수정
